# Generated by Django 2.2.3 on 2019-07-11 23:15

from django.db import migrations


class Migration(migrations.Migration):

    def capitlize(apps, schema_editor):
        Product = apps.get_model('main','Product')
        for product in Product.objects.all():
            product.name = product.name.capitalize()
            product.save()

    dependencies = [
        ('main', '0005_product_active'),
    ]

    operations = [
        migrations.RunPython(
            capitlize, #forward function
            migrations.RunPython.noop() #backward function
        )
    ]
